version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - cd app
            - echo Installing source NPM dependencies...
            - npm install
    pre_build:
        commands:
            - echo Pre-build started on `date`
            - echo Running tests...
            - npm run test
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $IMAGE_REPO_URL
            - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_URL:$IMAGE_TAG
    post_build:
        commands:
            - echo Pushing the Docker image...
            - docker push $IMAGE_REPO_URL:$IMAGE_TAG
            - echo Build completed on `date`
            - printf '[{"name":"$IMAGE_REPO_NAME","imageUri":"%s"}]' $IMAGE_REPO_URL:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
